from enum import Enum
import logging
from typing import Optional, List, Dict

## import mcp server
from mcp.server.models import InitializationOptions
from mcp.types import (
    TextContent,
    Tool,
    Resource,
    INTERNAL_ERROR,
    Prompt,
    PromptArgument,
    EmbeddedResource,
    GetPromptResult,
    PromptMessage, ErrorData,
)
from mcp.server import NotificationOptions, Server
from mcp.shared.exceptions import McpError
from pydantic import AnyUrl
import mcp.server.stdio
from pydantic import BaseModel

from mcp_server_ds.script_runner import ScriptRunner, RunScript

logger = logging.getLogger(__name__)
logger.info("Starting mini data science exploration server")


### Prompt templates
class DataExplorationPrompts(str, Enum):
    EXPLORE_DATA = "explore-data"


class PromptArgs(str, Enum):
    TOPIC = "topic"

PROMPT_TEMPLATE = """
你是一名专业的数据科学家，负责对一个数据集进行探索性数据分析。你的目标是提供有见地的分析，提出问题，并按步骤解决问题，同时确保稳定性和结果大小的可管理性。

你的分析应集中在以下主题：

<analysis_topic>
{topic}
</analysis_topic>

你可以使用以下工具进行分析：
1. run_script：用于在MCP服务器上执行Python脚本。

请仔细按照以下步骤进行：

2. 探索数据集。提供其结构的简要总结，包括行数、列数和数据类型。。** 包括：
   - 数据集的关键统计信息列表
   - 你在分析该数据时预见的潜在挑战

3. 你需要有一个思考过程：
   分析数据集的大小和复杂性：
   - 它有多少行和列？
   - 基于数据类型或数据量是否存在潜在的计算挑战？
   - 鉴于数据集的特点和分析主题，哪些问题是合适的？
   - 我们如何确保我们的问题不会导致过大的输出？

   基于此分析：
   - 列出与分析主题相关的10个潜在问题
   - 根据以下标准评估每个问题：
     * 直接与分析主题相关
     * 可以以合理的计算努力回答
     * 将产生可管理的结果大小
     * 提供对数据的有意义的见解
   - 选择最符合所有标准的前5个问题

4. 列出你选择的5个问题，确保它们符合上述标准。

5. 对每个问题，按照以下步骤进行：
   a. 你需要有一个思考过程：
      - 如何结构化Python脚本以有效回答这个问题？
      - 需要进行哪些数据预处理步骤？
      - 如何限制输出大小以确保稳定性？
      - 如何结合数据来说明结果？
      - 概述脚本将遵循的主要步骤

   b. 编写Python脚本回答问题。包括解释你的方法和任何限制输出大小的措施的注释。

   c. 使用run_script工具在MCP服务器上执行你的Python脚本。

   d. 详细描述run_script工具返回的结果，重点关注观察到的关键见解和模式。提供清晰简洁的文字总结，而不是使用图形表示。

6. 完成所有5个问题的分析后，提供你的发现和从数据中获得的任何总体见解的简要总结。

记住在分析中优先考虑稳定性和可管理性。如果在任何时候遇到潜在的结果集过大问题，请相应地调整你的方法。

请通过提供数据集的初步探索来开始你的分析。
"""
### Data Exploration Tools Description & Schema
class DataExplorationTools(str, Enum):
    RUN_SCRIPT = "run_script"


RUN_SCRIPT_TOOL_DESCRIPTION = """
Python Script Execution Tool

Purpose:
Execute Python scripts for specific data analytics tasks.

Allowed Actions
	1.	Print Results: Output will be displayed as the script's stdout.
	2.	[Optional] Save Dataframes: Save DataFrames to local disk by specifying a list of dictionaries, where each dictionary contains the dataframe name and the path where it should be saved. For example: `[{"df_name": "df_1", "path": "output/df_1.csv"}]`.

Prohibited Actions
	1.	Overwriting Original DataFrames: Do not modify existing DataFrames to preserve their integrity for future tasks.
	2.	Creating Charts: Chart generation is not permitted.
"""


### MCP Server Definition
async def main():
    script_runner = ScriptRunner()
    server = Server("local-mini-ds")

    @server.list_resources()
    async def handle_list_resources() -> list[Resource]:
        logger.debug("Handling list_resources request")
        return [
            Resource(
                uri="data-exploration://notes",
                name="Data Exploration Notes",
                description="Notes generated by the data exploration server",
                mimeType="text/plain",
            )
        ]

    @server.read_resource()
    async def handle_read_resource(uri: AnyUrl) -> str:
        logger.debug(f"Handling read_resource request for URI: {uri}")
        if uri == "data-exploration://notes":
            return "\n".join(script_runner.notes)
        else:
            raise ValueError(f"Unknown resource: {uri}")

    @server.list_prompts()
    async def handle_list_prompts() -> list[Prompt]:
        logger.debug("Handling list_prompts request")
        return [
            Prompt(
                name=DataExplorationPrompts.EXPLORE_DATA,
                description="A prompt to explore a csv dataset as a data scientist",
                arguments=[
                    PromptArgument(
                        name=PromptArgs.TOPIC,
                        description="The topic the data exploration need to focus on",
                        required=False,
                    ),
                ],
            )
        ]

    @server.get_prompt()
    async def handle_get_prompt(name: str, arguments: dict[str, str] | None) -> GetPromptResult:
        logger.debug(f"Handling get_prompt request for {name} with args {arguments}")
        if name != DataExplorationPrompts.EXPLORE_DATA:
            logger.error(f"Unknown prompt: {name}")
            raise ValueError(f"Unknown prompt: {name}")

        topic = arguments.get(PromptArgs.TOPIC)
        prompt = PROMPT_TEMPLATE.format(topic=topic)

        logger.debug(f"Generated prompt template for topic: {topic}")
        return GetPromptResult(
            description=f"Data exploration template for {topic}",
            messages=[
                PromptMessage(
                    role="user",
                    content=TextContent(type="text", text=prompt.strip()),
                )
            ],
        )

    @server.list_tools()
    async def handle_list_tools() -> list[Tool]:
        logger.debug("Handling list_tools request")
        return [
            Tool(
                name=DataExplorationTools.RUN_SCRIPT,
                description=RUN_SCRIPT_TOOL_DESCRIPTION,
                inputSchema=RunScript.model_json_schema(),
            )
        ]

    @server.call_tool()
    async def handle_call_tool(
            name: str, arguments: dict | None
    ) -> list[TextContent | EmbeddedResource]:
        logger.debug(f"Handling call_tool request for {name} with args {arguments}")
        if name == DataExplorationTools.RUN_SCRIPT:
            script = arguments.get("script")
            save_to_memory = arguments.get("save_to_memory")
            return script_runner.safe_eval(script, save_to_memory)
        else:
            raise McpError(ErrorData(code=INTERNAL_ERROR, message=f"Unknown tool: {name}"))


    async with mcp.server.stdio.stdio_server() as (read_stream, write_stream):
        logger.debug("Server running with stdio transport")
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="data-exploration-server",
                server_version="0.1.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


